DEST_LANGS_TURKIC = (
('Salar', 'slr'),
('Ottoman Turkish', 'ota'),
('Pecheng', 'xpc'),
('Turkish', 'tr'),
('Gaguaz', 'gag'),
('Azerbaijani', 'az'),
('Turkmen', 'tk'),
('Khorasani Turkish', 'kmz'),
("Qashqa'i", "qxq"),
('Khalaf', 'kjf'),
('Kumyk', 'kum'),
('Karachay-Balkar', 'krc'),
('Crimean Turkish', 'crh'),
('Urum', 'uum'),
('Krymchak', 'jct'),
('Karaim', 'kdr'),
('Tatar', 'tt'),
('Bashkir', 'ba'),
('Kazakh', 'kk'),
('Kyrgyz', 'ky'),
('Uzbek', 'uz'),
('Ili Turki', 'ili'),
('Chagatai', 'chg'),
('Khorezmian', 'zkh'),
('Karakhanid', 'xqa'),
('Sakha', 'sah'),
('Dolgan', 'slg'),
('Chulym', 'clw'),
('Khakas', 'kjh'),
('Kuman', 'qwm'),
('Northern Altai', 'atv'),
('Southern Altai', 'alt'),
('East Yugur', 'yuy'),
('West Yugur', 'ybe'),
('Kyrgyz', 'ky'),
('Chuvash', 'cv'),
('Khazar', 'zkz'),
)

DEST_LANGS_URALIC = (
('Finnish', 'fi'),
('Estonian', 'et'),
('Karelian', 'krl'),
('Võro', 'vor'),
('Veps', 'vep'),
('Ingrian', 'izh'),
('Votic', 'vot'),
('Khanty', 'kca'),
('Mansi', 'mns'),
('Hungarian', 'hu'),
('Nganasan' ,'nio'),
('Mator' ,'mtm'),
('Mator-Taygi-Karagas' ,'ymt'),
('Nenets' ,'yrk'),
('Forest Enets' ,'enf'),
('Tundra Enets' ,'enh'),
('Selkup' ,'sel'),
('South Selkup	mis' ,'sel'),
('Kamas' ,'xas'),
('Old Hungarian' ,'ohu'),
('Komi-Permyak' ,'koi'),
('Udmurt' ,'udm'),
('Kom' ,'kv'),
('Komi-Permyak' ,'koi'),
('Komi-Zyrian' ,'kpv'),
('Mari (Russia)' ,'chm'),
('Eastern Mari' ,'mhr'),
('Western Mari' ,'mrj'),
('Erzya' ,'myv'),
('Moksha' ,'mdf'),
('Liv' ,'liv'),
('Livvi' ,'olo'),
('Ingrian' ,'izh'),
('Ludian' ,'lud'),
('Akkala Sami' ,'sia'),
('Inari Sami' ,'smn'),
('Kemi Sami' ,'sjk'),
('Kildin Sami' ,'sjd'),
('Lule Sami' ,'smj'),
('Northern Sam' ,'	se'),
('Pite Sami' ,'sje'),
('Skolt Sami' ,'sms'),
('Southern Sami' ,'sma'),
('Ter Sami' ,'sjt'),
('Ume Sami' ,'sju'),
)

DEST_LANGS_TUNGUSIC = (
('Jurchen', 'juc'),
('Manchu', 'mnc'),
('Xibe', 'sjo'),
('Nanai', 'gld'),
('Orok', 'oaa'),
('Ulch', 'ulc'),
('Oroch', 'oac'),
('Even', 'eve'),
('Evenki', 'evn'),
('Negidal', 'neg'),
('Oroqen', 'orh'),
)

DEST_LANGS_REST = (
('Chinese', 'zh'),
('Late Middle Chinese', 'ltc'),
('Old Chinese', 'och'),
('Tibetan', 'bo'),
('Classical Tibetan', 'xct'),
('Old Tibetan', 'otb'),
('Burmese', 'my'),
('Latin', 'la'),
('Ancient Greek', 'grc'),
('Quechua', 'qu'),
('Qeuchan', 'yum'),
('Ainu', 'ain'),
('Vietnamese', 'vi'),
('Sanskrit', 'sa'),
)

DEST_LANGS_DICT ={
    'u' : DEST_LANGS_URALIC,
    't' : DEST_LANGS_TUNGUSIC,
    'r' : DEST_LANGS_TURKIC,
    's' : DEST_LANGS_REST,
}